version: '3'

services:
  myapp:
    image: main-microservice-image:latest
    container_name: main-microservice
    environment:
      - DB_ENABLED=true
      - QUEUE_ENABLED=true
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db
    ports:
      - "80:8080"
    command: sh -c "java -jar gymApp-0.0.1-SNAPSHOT.jar"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
